name: wiggly_env12
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - asttokens
  - attrs
  - blas
  - blosc
  - boost-cpp
  - bottleneck
  - branca
  - brotli
  - brotli-python
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - fiona
  - folium
  - fontconfig
  - fonttools
  - freetype
  - freexl
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - glib
  - glib-tools
  - h5py
  - hdf4
  - hdf5
  - icc_rt
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libcurl
  - libdeflate
  - libffi
  - libgdal
  - libglib
  - libiconv
  - libkml
  - libnetcdf
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - libzip
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib-base
  - minizip
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nest-asyncio
  - networkx
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - poppler
  - poppler-data
  - proj
  - psutil
  - pure_eval
  - pygments
  - pyparsing
  - pyproj
  - pysocks
  - python-dateutil
  - python-tzdata
  - pytz
  - pywin32
  - pyzmq
  - qhull
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - sqlite
  - stack_data
  - tbb
  - threadpoolctl
  - tiledb
  - tk
  - tornado
  - typing_extensions
  - tzdata
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - wheel
  - win_inet_pton
  - xerces-c
  - xyzservices
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - anytree
      - black
      - cftime
      - circle-fit
      - fastjsonschema
      - imageio
      - iniconfig
      - ipympl
      - ipython
      - ipython-genutils
      - ipywidgets
      - jsonschema
      - jsonschema-specifications
      - jupyterlab-widgets
      - lazy-loader
      - llvmlite
      - matplotlib-inline
      - meanderpy
      - motionless
      - mypy-extensions
      - nbformat
      - netcdf4
      - numba
      - parso
      - pathspec
      - patsy
      - plotly
      - pluggy
      - prompt-toolkit
      - pyarrow
      - pytest
      - python-dotenv
      - referencing
      - rpds-py
      - salem
      - scikit-image
      - seaborn
      - simpledbf
      - stack-data
      - statsmodels
      - tenacity
      - tifffile
      - tqdm
      - traitlets
      - widgetsnbextension
      - xarray
