name: Python Package using Conda

on:
  pull_request:
    branches: [stable]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge geopandas
          conda install -c conda-forge h5py
          pip install simpledbf
          pip install statsmodels
          pip install seaborn
          pip install pyarrow
          pip install plotly
          pip install salem
          pip install anytree
          pip install circle-fit
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
