name: Python Package using Conda

on:
  pull_request:
    branches: [stable]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          conda create -n wiggly_test python=3.10
          conda init
          conda activate wiggly_test
          conda install -c conda-forge geopandas
          conda install -c conda-forge h5py
          pip install simpledbf
          pip install statsmodels
          pip install seaborn
          pip install pyarrow
          pip install plotly
          pip install salem
          pip install anytree
          pip install circle-fit
          pip install tqdm
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
