name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # Add permissions for GitHub pages
    permissions:
      contents: write
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge geopandas
          conda install -c conda-forge h5py
          pip install simpledbf
          pip install statsmodels
          pip install seaborn
          pip install pyarrow
          pip install plotly
          pip install salem
          pip install anytree
          pip install circle-fit
          pip install tqdm
          pip install Sphinx
          pip install sphinx_rtd_theme
          pip install ghp-import
          # Install your package in editable mode
          pip install -e .
      - name: Build documentation
        run: |
          cd docs
          make html
          # Check if the build was successful
          if [ ! -f _build/html/index.html ]; then
            echo "Documentation build failed!"
            exit 1
          fi
      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f docs/_build/html
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
